### ISSUE TITLE
EasyEdge-Free

### ISSUE THREAD

**Issue by private1215** [TheLittleBoy/TextDetection-VIN#6]
兄弟，EasyEdge-Free最原始的可以下载时的demo源码你还要吗，现在的都得要序列号了

**Comment by TheLittleBoy** [comment]
推荐另外一个非EasyEdge项目：https://github.com/TheLittleBoy/TextDetection-VIN3

**Comment by private1215** [comment]
这个paddleocr有了，百度AI这里paddleocr和easyedge识别稳定性，easyedge更好一些，但是只有APK，官方也说没开源，我感觉应该是以前开源过一段时间，就是EasyEdge-Free开源的ocr模型，不需要序列号的版本，我是搜到你这里，冒昧问下

**Comment by private1215** [comment]
兄弟，我解决了多谢回复
